apiVersion: v1
kind: Service
metadata:
  name: auth-admin-ui
  namespace: henderson
  labels:
    app.kubernetes.io/name: auth-admin-ui
    app.kubernetes.io/part-of: tigersoft-auth
spec:
  type: ClusterIP
  selector:
    app: auth-admin-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
